### PR TITLE
Fix #5741 don't crash when vkCreateDevice fails

### LINKED ISSUE #5741: App crashes when vkCreateDevice fails
## error log | 日志或报错信息 | ログ
```
[0 Intel(R) Iris(R) Xe Graphics] queueC=0[1] queueG=0[1] queueT=0[1]
[0 Intel(R) Iris(R) Xe Graphics] bugsbn1=0 bugbilz=0 bugcopc=0 bugihfa=0
[0 Intel(R) Iris(R) Xe Graphics] fp16-p/s/a=1/1/1 int8-p/s/a=1/1/1
[0 Intel(R) Iris(R) Xe Graphics] subgroup=32 basic/vote/ballot/shuffle=1/1/1/1
[0 Intel(R) Iris(R) Xe Graphics] fp16-matrix-16_8_8/16_8_16/16_16_16=0/0/0
vkCreateDevice failed -4
Segmentation fault
```
## context | 编译/运行环境 | バックグラウンド

My app crashes on some systems where there is some problems with Vulkan. It should fallback to CPU instead in such cases.

## how to reproduce | 复现步骤 | 再現方法

1. Run system where vkCreateDevice fails or replace vkCreateDevice call with `VkResult ret = VK_ERROR_DEVICE_LOST;`
2. Run the simplest application:
```
#include <ncnn/net.h>
int main() {
    ncnn::get_gpu_device(0);
    ncnn::destroy_gpu_instance();
    return 0;
}
```

### PR DESCRIPTION
**Pull request by Upliner**
This patch should fix #5741 and prevent crash if vkCreateDevice fails or unable to create dummy buffer image.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5742) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=5742) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=5742) it.</sub>

File: src/net.cpp [hunk 1]
```diff
@@ -1381,7 +1381,7 @@ int Net::load_param(const DataReader& dr)
     if (opt.use_vulkan_compute)
     {
         if (!d->vkdev) d->vkdev = get_gpu_device();
-        if (!d->vkdev) opt.use_vulkan_compute = false; // no vulkan device, fallback to cpu
+        if (!d->vkdev || !d->vkdev->is_valid()) opt.use_vulkan_compute = false; // no valid vulkan device, fallback to cpu
```
Comment (nihui) [inline src/net.cpp:1384]: and apply this change to `Net::load_param_bin` too

**Review by nihui — CHANGES_REQUESTED** [review]

**Review by nihui — APPROVED** [review]

**Comment by nihui** [comment]
Thanks for your contribution !
