### PR TITLE
fix #1984 & fix cmake 

### LINKED ISSUE #1984: clang5.0 didn't support __builtin_cpu_init
System information (version)
- Version =>20200722
- Operating System / Platform => ubuntu14.04
- Compiler =>clang 5.0.2

I get the error:
cpu.cpp:240:5: error: use of undeclared identifier '__builtin_cpu_init'

### PR DESCRIPTION
**Pull request by zchrissirhcz**
fix #1984 as nihui already pointed out

fix cmake < 3.6 + opencv 4 caused example folder build error, e.g. ubuntu 16.04 + own compiled opencv 4

### CODE REVIEW

File: src/cpu.cpp [hunk 1]
```diff
@@ -237,7 +237,9 @@ int cpu_support_x86_avx2()
     return cpu_info[1] & 0x00000020;
 #else
     // TODO gcc-specific
-    __builtin_cpu_init();
+    #if !(defined(__clang__) & __clang_major__ < 6)
+        __builtin_cpu_init();
+    #endif
```
Comment (nihui) [inline src/cpu.cpp:242]: &&
style fix ?

Comment (zchrissirhcz) [reply src/cpu.cpp:242]: 好，稍等

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2000) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/ncnn?pullRequest=2000) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: zchrissirhcz<br/>:x: restyled-commits<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/ncnn?pullRequest=2000) it.</sub>

File: src/cpu.cpp [hunk 2]
```diff
@@ -214,7 +214,7 @@ int cpu_support_arm_asimdhp()
 
 int cpu_support_x86_avx2()
 {
-#if defined(__x86_64__)
+#if defined(__x86_64__) || defined(_WIN32)
```
Comment (nihui) [inline src/cpu.cpp:217]: _M_AMD64 Defined as the integer literal value 100 for compilations that target x64 processors. Otherwise, undefined.
https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019
https://sourceforge.net/p/predef/wiki/Architectures/

File: src/cpu.cpp [hunk 3]
```diff
@@ -235,9 +235,10 @@ int cpu_support_x86_avx2()
 
     __cpuid(cpu_info, 7);
     return cpu_info[1] & 0x00000020;
-#else
-    // TODO gcc-specific
+#elif defined(__clang__) || defined(__GNUC__)
+#if __clang_major__ >= 6
     __builtin_cpu_init();
+#endif
```
Comment (nihui) [inline src/cpu.cpp:241]: gcc 可能没有 __clang_major__ >= 6，会导致没有调用 __builtin_cpu_init()

**Comment by thtfpcuser** [comment]
不知道avx2判断方法 ，应输出提示信息。Prompt message is needed to output, when avx2 detection method is unknown.

File: src/cpu.cpp [hunk 4]
```diff
@@ -235,10 +235,18 @@ int cpu_support_x86_avx2()
...
     return __builtin_cpu_supports("avx2");
+#elif defined(__GNUC__)
+    __builtin_cpu_init();
+    return __builtin_cpu_supports("avx2");
+#else
+    // TODO: other x86 compilers checking avx2 here
+    fprintf(stderr, "AVX2 detection method is unknown for current compiler. See file %s, line %d\n", __FILE__, __LINE__);
```
Comment (nihui) [inline src/cpu.cpp:248]: 改成 NCNN_LOGE() 实现，然后 ```__FILE__``` ```__LINE__``` 没必要输出出来的
辛苦了。。
```
NCNN_LOGE("AVX2 detection method is unknown for current compiler");
```

**Comment by nihui** [comment]
Thanks !
